[crowsnest]
log_path: /home/pi/printer_data/logs/crowsnest.log
log_level: quiet
delete_log: false
no_proxy: false

[cam 1]
mode: camera-streamer
enable_rtsp: true
rtsp_port: 8554
port: 8080
device: /dev/video0 # Stock camera
#device: /dev/v4l/by-id/usb-UnionImage_Co._Ltd_CCX2F3298_1234567890-video-index0 # Nebula camera
resolution: 1280x960
max_fps: 30