# This file stores the flash_commands for each mcus
# Previous version KCONFIG_CONFIG was needed now it is automaticly added when make flash is called
# version : 0.1
# tested/supported flash methods :
#  - make flash
#  - sdcard_flash
#  - flashtool.py
#  - mount/cp/umount (for rp2040)

[qidi_mainboard]
klipper_section: mcu
action_command: ~/klippy-env/bin/python3 ~/katapult/scripts/flashtool.py -d /dev/serial/by-id/usb-katapult_stm32f401xc_1F0034000950324257333720-if00 -b 500000

[qidi_toolhead]
klipper_section: mcu
action_command: ~/klippy-env/bin/python3 ~/katapult/scripts/flashtool.py -d /dev/serial/by-id/usb-Silicon_Labs_CP2102_USB_to_UART_Bridge_Controller_0001-if00-port0 -b 500000

[rpi]
klipper_section: mcu host
action_command: make flash

[toquecan]
klipper_section: mcu toquecan
quiet_command: ~/klippy-env/bin/python3 ~/katapult/scripts/flashtool.py -i can0 -r -u 0f474d645f9a; sleep 2
action_command: ~/klippy-env/bin/python3 ~/katapult/scripts/flashtool.py -d /dev/serial/by-id/usb-katapult_stm32f072xb_310042001957464E33323420-if00